name: Angular MFE Build
description: "Build and artifact"

inputs:
  commitId:
    type: string
    description: Commit Id to build
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Checkout Branch
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.commitId }}
        path: application
    - name: Get project name
      shell: bash
      id: ngproj
      run: echo "name=$(jq -r '.defaultProject // (.projects | keys[0])' angular.json)" >> $GITHUB_OUTPUT
      working-directory: application/client
    - name: Install Node v24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
        cache-dependency-path: application/client/package-lock.json
    - name: Install Node Dependencies
      shell: bash
      run: npm ci
      working-directory: application/client
    - name: Build Application
      shell: bash
      run: npm run build -- --base-href /${{ steps.ngproj.outputs.name }}/
      working-directory: application/client
    - name: Create Artifact
      uses: actions/upload-artifact@v7
      with:
        path: application/client/dist/${{ steps.ngproj.outputs.name }}/browser/*
        name: client-artifact
